import type { NextPage } from "next";
import Head from "next/head";
import ProjectCard from "components/ProjectCard";

const Home: NextPage = () => {
  return (
    <div className="mt-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="mb-8">My Portfolio</h1>
      <div className="grid grid-cols-2 gap-4">
        <ProjectCard />
        <ProjectCard />
        <ProjectCard />
        <ProjectCard />
      </div>
    </div>
  );
};

export default Home;
