import type { NextPage } from "next";
import Head from "next/head";
import Header from "components/Header";
import Footer from "components/Footer";

const Home: NextPage = () => {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <h1>My Portfolio</h1>
      </main>
      <Footer />
      
    </div>
  );
};

export default Home;
